coverage:
  precision: 2
  round: down
  range: "70..100"
  ignore:
    - "apis/**/*"
    - "docs/**/*.go"
    - "internal/rbac/**/*"
    - "internal/dynamic/**/*"
    - "plumbing/e2e/**/*"
    - "plumbing/endpoints/**/*"
