---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: bff
  namespace: demo-system
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: demo-system
spec:
  selector:
    app: bff
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: demo-system
  labels:
    app: bff
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      serviceAccountName: bff
      containers:
      - name: krateo-bff
        image: kind.local/bff:latest
        imagePullPolicy: Never
        args:
          - --debug=true
          - --dump-env=true
          - --authn-store-namespace=demo-system
        ports:
        - name: http
          containerPort: 8081
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bff
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bff
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bff
subjects:
- kind: ServiceAccount
  name: bff
  namespace: demo-system
