name: release-pullrequest

on:
  pull_request:
    branches:
      - main

env:
  GHCR_REPO: ghcr.io/${{ github.repository }}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Gather dependencies
        run: go mod download
      - name: Run coverage
        run: go test -race -tags=unit,integration -p 1 -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
